name: i2v_adapter
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.12
  - pytorch=2.3
  - torchvision=0.17
  - pytorch-cuda=12.0
  - pip
  - pip:
    - diffusers==0.29
    - transformers==4.25.1
    - xformers==0.0.16
    - imageio==2.27.0
    - decord==0.6.0
    - gdown
    - einops
    - omegaconf
    - safetensors
    - gradio
    - wandb